apiVersion: apps/v1
kind: Deployment
metadata:
  name: soojung
  labels:
    app: soojung
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: soojung
  template:
    metadata:
      labels:
        app: soojung
    spec:
      containers:
      - name: my-image
        image: so21yeon11/my-image:latest
        ports:
        - containerPort: 80
          name: soojung
---
apiVersion: v1
kind: Service
metadata:
  name: soojung
  labels:
    app: soojung
spec:
  ports:
  - name: soojung
    nodePort: 30401
    port: 8081
    targetPort: 80
  selector:
    app: soojung
  type: LoadBalancer

